# Generated by Django 6.0.4 on 2026-05-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usd_to_cop_rate',
            field=models.DecimalField(decimal_places=2, default=4200, max_digits=10),
        ),
    ]
