# Generated by Django 6.0.4 on 2026-05-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_transaction_type_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("telegram", "Telegram"),
                    ("claude", "Claude"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
